fixed bugs

diff --git a/copydb b/copydb
--- a/copydb
+++ b/copydb
@@ -1,7 +1,10 @@
 #!/bin/bash
 
 E_OPTION_ERROR=1
-E_INPUT_TYPE_ERROR=5
+E_SOURCE_FILE_NOT_FOUND=10
+E_CANT_READ_SOURCE_FILE=8
+E_SOURCE_TYPE_ERROR=21
+E_INVALID_SOURCE_FILE=29
 E_FAIL_ERROR=5
 COMMAND=`basename $0`
 
@@ -22,7 +25,7 @@ main()
 ##############################################################################
 {
   # notify when any command fails
-  add_on_err 'printf "\n${TXT_FAIL}*****  $COMMAND FAILED  *****${TXT_NORMAL}\n\n"'
+  add_on_exit 'printf "\n${TXT_FAIL}*****  $COMMAND FAILED  *****${TXT_NORMAL}\n\n"'
 
   get_options "$@"
 
@@ -302,32 +305,10 @@ set_date()
 on_exit()
 ##############################################################################
 {
-  for i in "${on_exit_items[@]}"; do
-    eval $i
-  done
-}
-
-
-##############################################################################
-add_on_exit()
-##############################################################################
-{
-  local n=${#on_exit_items[*]}
-  on_exit_items[$n]="$*"
-  if [[ $n -eq 0 ]]; then
-    trap on_exit EXIT
-  fi
-}
-
-
-##############################################################################
-on_err()
-##############################################################################
-{
   exitCode=$?
 
-  if [[ $exitCode == 5 ]]; then
-    for i in "${on_err_items[@]}"; do
+  if [[ $exitCode == $E_FAIL_ERROR ]]; then
+    for i in "${on_exit_items[@]}"; do
       eval $i
     done
   fi
@@ -337,14 +318,14 @@ on_err()
 
 
 ##############################################################################
-add_on_err()
+add_on_exit()
 ##############################################################################
 {
-  local n=${#on_err_items[*]}
-  on_err_items[$n]="$*"
-  if [[ $n -eq 0 ]]; then
+  local n=${#on_exit_items[*]}
+  on_exit_items[$n]="$*"
+  if [ $n -eq 0 ]; then
     set -E -o pipefail
-    trap on_err EXIT
+    trap on_exit EXIT
   fi
 }
 
@@ -409,7 +390,7 @@ run_command()
   fi
 
   if [ -n "$fail_command" ]; then
-    add_on_err $fail_command
+    add_on_exit $fail_command
   fi
 
   _run_command "$command"
@@ -421,7 +402,7 @@ run_command()
     else
       printf "${TXT_ERROR}###   [ FAIL ]   ###${TXT_NORMAL}\n"
       if [ "$error_handling" == "fail" ]; then
-        exit 5    # Trap Error & Exit
+        exit $E_FAIL_ERROR    # Trap Error & Exit
       fi
     fi
   fi
@@ -450,48 +431,39 @@ optionally_compress_file()
   filename=$1
 
   if [ -n "$bzip2" ]; then
+    printf "\n${TXT_NOTICE}## Compressing file with bzip2: \"$filename\"${TXT_NORMAL}\n"
+
     command="bzip2 $original_file"
 
-    printf "\n${TXT_NOTICE}## Compressing file with bzip2: \"$filename\"${TXT_NORMAL}\n"
     output_command "$command"
     run_command "$command" "" "fail"
 
   elif [ -n "$gzip" ]; then
+    printf "\n${TXT_NOTICE}## Compressing file with gzip: \"$filename\"${TXT_NORMAL}\n"
+
     command="gzip $original_file"
 
-    printf "\n${TXT_NOTICE}## Compressing file with gzip: \"$filename\"${TXT_NORMAL}\n"
     output_command "$command"
     run_command "$command" "" "fail"
   fi
 }
 
 
-
 ##############################################################################
-redirect_to_output()
+output_source_file_command()
 ##############################################################################
 {
-  output_file=$1
-  redirection=""
+  source_file=$1
 
-  if [ -n "$bzip2" ]; then
-    redirection="| bzip2 -c "
-  elif [ -n "$gzip" ]; then
-    redirection="| gzip -c "
+  if [ ! -e "$source_file" ]; then
+    exit $E_SOURCE_FILE_NOT_FOUND
+  elif [ ! -f "$source_file" ]; then
+    exit $E_INVALID_SOURCE_FILE
+  elif [ ! -r "$source_file" ]; then
+    exit $E_CANT_READ_SOURCE_FILE
   fi
 
-  redirection_output="$redirection> '$output_file'"
-
-  echo $redirection_output
-}
-
-
-##############################################################################
-redirect_from_input()
-##############################################################################
-{
-  input_file=$1
-  mime_type=$(file -ib "$1")
+  mime_type=$(file -ib "$source_file")
 
   case $mime_type in
     *text/plain*)
@@ -504,13 +476,11 @@ redirect_from_input()
       input_process="gzip -dc"
       ;;
     *)
-      printf "\n${TXT_ERROR}$COMMAND: input format not supported${TXT_NORMAL}\n"
-      help_prompt
-      exit $E_INPUT_TYPE_ERROR
+      exit $E_SOURCE_TYPE_ERROR
       ;;
   esac
 
-  redirection_input="${input_process} '$input_file'"
+  redirection_input="${input_process} '$source_file'"
 
   echo $redirection_input
 }
@@ -520,12 +490,12 @@ redirect_from_input()
 backup_source_db()
 ##############################################################################
 {
+  printf "\n\n${TXT_NOTICE}## Creating dump of source database: \"$source_db\"${TXT_NORMAL}\n"
+
   # set source output filename
   source_db_output=$(output_filename 'source' "$source_db")
 
   command="mysqldump -u '$db_username'<password> '$source_db' > $source_db_output"
-
-  printf "\n\n${TXT_NOTICE}## Creating dump of source database: \"$source_db\"${TXT_NORMAL}\n"
 
   output_command "$command" "$source_db_output"
   run_command "$command" "$source_db_output" "fail" "rm -f $source_db_output"
@@ -538,10 +508,10 @@ backup_source_db()
 check_db_connection()
 ##############################################################################
 {
+  printf "\n\n${TXT_NOTICE}## Checking database connection...${TXT_NORMAL}\n"
+
   # check if destination database exists
   command="mysql --batch --skip-column-names -u '$db_username'$db_password_out -e 'connect'"
-
-  printf "\n\n${TXT_NOTICE}## Checking database connection...${TXT_NORMAL}\n"
 
   run_command "$command" "" "fail"
 }
@@ -551,10 +521,10 @@ check_db_connection()
 check_for_destination_db()
 ##############################################################################
 {
+  printf "\n\n${TXT_NOTICE}## Checking if destination database exists: \"$destination_db\"${TXT_NORMAL}\n"
+
   # check if destination database exists
   command="mysql --batch --skip-column-names -u '$db_username'$db_password_out -e 'SHOW DATABASES LIKE \"$destination_db\"' | grep -q '$destination_db'"
-
-  printf "\n\n${TXT_NOTICE}## Checking if destination database exists: \"$destination_db\"${TXT_NORMAL}\n"
 
   run_command "$command" "" "silent"
   return_code=$?
@@ -576,12 +546,12 @@ backup_destination_db()
   check_for_destination_db
 
   if [ "$?" -eq "0" ]; then
+    printf "${TXT_NOTICE}## Backing up: \"$destination_db\"${TXT_NORMAL}\n"
+
     # set destination output filename
     destination_db_output=$(output_filename 'destination' "$destination_db")
 
     command="mysqldump -u '$db_username'<password> '$destination_db' > $destination_db_output"
-
-    printf "${TXT_NOTICE}## Backing up: \"$destination_db\"${TXT_NORMAL}\n"
 
     output_command "$command" "$destination_db_output"
     run_command "$command" "$destination_db_output" "fail" "rm -f $destination_db_output"
@@ -598,9 +568,9 @@ backup_destination_db()
 create_destination_db()
 ##############################################################################
 {
-  command="mysql -u '$db_username'<password> -e 'DROP DATABASE IF EXISTS \`$destination_db\`; CREATE DATABASE \`$destination_db\` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;'"
-
   printf "\n\n${TXT_NOTICE}## Creating empty destination database: \"$destination_db\"${TXT_NORMAL}\n"
+
+  command="mysql -u '$db_username'<password> -e 'DROP DATABASE IF EXISTS \`$destination_db\`; CREATE DATABASE \`$destination_db\` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;'"
 
   output_command "$command"
   run_command "$command" "" "fail"
@@ -613,12 +583,41 @@ copy_source_to_destination_db()
 {
   source_db_file=$1
 
-  command="$(redirect_from_input "$source_db_file") | mysql -u '$db_username'<password> '$destination_db'"
+  printf "\n\n${TXT_NOTICE}## Copying source to destination database: \"$destination_db\"${TXT_NORMAL}\n"
 
-  printf "\n\n${TXT_NOTICE}## Copying source database dump to destination database: \"$destination_db\"${TXT_NORMAL}\n"
+  output_source_file_command="$(output_source_file_command $source_db_file)"
+  return_code=$?
 
-  output_command "$command" "$outfile"
-  run_command "$command" "$outfile" "fail" "rm -f $outfile"
+  case $return_code in
+    0)
+      command="$output_source_file_command | mysql -u '$db_username'<password> '$destination_db'"
+      output_command "$command" "$outfile"
+      run_command "$command" "$outfile" "fail" "rm -f $outfile"
+      ;;
+    $E_SOURCE_FILE_NOT_FOUND)
+      output="${TXT_ERROR}$COMMAND: source file not found${TXT_NORMAL}\n"
+      ;;
+    $E_CANT_READ_SOURCE_FILE)
+      output="${TXT_ERROR}$COMMAND: cannot read source file${TXT_NORMAL}\n"
+      ;;
+    $E_SOURCE_TYPE_ERROR)
+      output="${TXT_ERROR}$COMMAND: source format not supported${TXT_NORMAL}\n"
+      ;;
+    $E_INVALID_SOURCE_FILE)
+      output="${TXT_ERROR}$COMMAND: invalid source file${TXT_NORMAL}\n"
+      ;;
+    *)
+      output="${TXT_ERROR}$COMMAND: problem with source file${TXT_NORMAL}\n"
+      ;;
+  esac
+
+  if [ $return_code != 0 ]; then
+    printf "$output"
+    printf "${TXT_ERROR}###   [ FAIL ]   ###${TXT_NORMAL}\n"
+    exit $E_FAIL_ERROR
+  else
+    printf "${TXT_SUCCESS}###   [ PASS ]   ###${TXT_NORMAL}\n"
+  fi
 }
 
 
